# Credenciales localessssss para desarrollo
DB_URL=jdbc:mysql://localhost:3306/ingeniera_global_ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
DB_USERNAME=root
DB_PASSWORD=152277
JWT_SECRET=NJlYMJDI1/fZ282/TrtQLu9NSNK52rxv/5Cj+Mmn4uA=
MAIL_USERNAME=ingenieriaglobalgrupoig@gmail.com
MAIL_PASSWORD=pzncocweicjwbuge
MAIL_REMITENTE=ingenieriaglobalgrupoig@gmail.com
MAIL_DESTINATARIO=ingenieriaglobalgrupoig@gmail.com
FRONTEND_URL=http://localhost:4200
CLOUDINARY_CLOUD_NAME=m83d3tuw
CLOUDINARY_API_KEY=961813819235239
CLOUDINARY_API_SECRET=1QXbLwzQv_E8j6s2WIdCIBw1A7o